Repeat the previous exercise, but inside the catch clause, wrap g()'s exception in a RuntimeException.

Chapter 12 Exercise 11