Show that WithFinally.java doesn't fail by throwing a RuntimeException in the try block.

Chapter 12 Exercise 15